services:
  # 1. Banco de Dados Relacional da Ótica
  retsys_db:
    image: postgres:16-alpine
    container_name: retsys_postgres_container
    restart: always
    environment:
      POSTGRES_USER: retsys_dev
      POSTGRES_PASSWORD: SenhaSeguraOtica2026
      POSTGRES_DB: retsys_db_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - retsys_network

  # 2. Motor de IA Local para OCR das Receitas Óticas
  ollama:
    image: ollama/ollama:latest
    container_name: retsys_ollama_container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - retsys_network

  # 3. A Aplicação Web (C# .NET 10 + Vue 3 SPA)
  retsys_app:
    build:
      context: .
      dockerfile: RETSYS.Web/Dockerfile
    container_name: retsys_app_container
    restart: always
    ports:
      - "5000:8080" # Acessível no navegador via http://localhost:5000
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # CORRIGIDO: Alterado de DefaultConnection para ConexaoPadrao para casar com o seu Program.cs
      - ConnectionStrings__ConexaoPadrao=Host=retsys_db;Port=5432;Database=retsys_db_prod;Username=retsys_dev;Password=SenhaSeguraOtica2026;
    depends_on:
      - retsys_db
      - ollama
    networks:
      - retsys_network

networks:
  retsys_network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data: